<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Saurabh Shukla',
                'email' => 'saurabh.shukla@example.com',
                'profile_image' => 'saurabh.jpg',
                'gender' => 'male',
                'age' => 30,
                'dob' => '1993-11-24',
                'is_admin' => 1,
                'password' => Hash::make('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Anjali Verma',
                'email' => 'anjali.verma@example.com',
                'profile_image' => 'anjali.jpg',
                'gender' => 'female',
                'age' => 28,
                'dob' => '1995-02-15',
                'is_admin' => 0,
                'password' => Hash::make('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Rahul Mehta',
                'email' => 'rahul.mehta@example.com',
                'profile_image' => null,
                'gender' => 'male',
                'age' => 35,
                'dob' => '1988-08-10',
                'is_admin' => 0,
                'password' => Hash::make('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Priya Singh',
                'email' => 'priya.singh@example.com',
                'profile_image' => 'priya.jpg',
                'gender' => 'female',
                'age' => 26,
                'dob' => '1997-07-01',
                'is_admin' => 0,
                'password' => Hash::make('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Amit Jain',
                'email' => 'amit.jain@example.com',
                'profile_image' => null,
                'gender' => 'male',
                'age' => 40,
                'dob' => '1983-01-22',
                'is_admin' => 0,
                'password' => Hash::make('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Meena Sharma',
                'email' => 'meena.sharma@example.com',
                'profile_image' => 'meena.png',
                'gender' => 'female',
                'age' => 31,
                'dob' => '1992-05-11',
                'is_admin' => 0,
                'password' => Hash::make('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Ravi Kapoor',
                'email' => 'ravi.kapoor@example.com',
                'profile_image' => null,
                'gender' => 'male',
                'age' => 29,
                'dob' => '1994-03-08',
                'is_admin' => 0,
                'password' => Hash::make('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Sneha Rao',
                'email' => 'sneha.rao@example.com',
                'profile_image' => 'sneha.jpg',
                'gender' => 'female',
                'age' => 32,
                'dob' => '1991-09-20',
                'is_admin' => 0,
                'password' => Hash::make('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Vikas Nair',
                'email' => 'vikas.nair@example.com',
                'profile_image' => 'vikas.png',
                'gender' => 'male',
                'age' => 33,
                'dob' => '1990-06-17',
                'is_admin' => 0,
                'password' => Hash::make('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Tanya Malik',
                'email' => 'tanya.malik@example.com',
                'profile_image' => null,
                'gender' => 'female',
                'age' => 27,
                'dob' => '1996-12-30',
                'is_admin' => 0,
                'password' => Hash::make('123456'),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
